require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
